<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.sutran.sd</groupId>
        <artifactId>sutran-sd-modules</artifactId>
        <version>0.0.1</version>
    </parent>

    <artifactId>sutran-sd-module-draw</artifactId>

    <description>
        SD绘图公共模块
    </description>

    <dependencies>

        <!-- forest依赖 -->
        <dependency>
            <groupId>com.dtflys.forest</groupId>
            <artifactId>forest-spring-boot-starter</artifactId>
        </dependency>

        <!-- common依赖 -->
        <dependency>
            <groupId>com.sutran.sd</groupId>
            <artifactId>sutran-sd-common</artifactId>
        </dependency>

        <!-- OSS功能模块 -->
        <dependency>
            <groupId>com.sutran.sd</groupId>
            <artifactId>sutran-sd-module-oss</artifactId>
        </dependency>

        <!-- system模块 -->
        <dependency>
            <groupId>com.sutran.sd</groupId>
            <artifactId>sutran-sd-module-system</artifactId>
        </dependency>

<!--        <dependency>-->
<!--            <groupId>com.alibaba.fastjson2</groupId>-->
<!--            <artifactId>fastjson2</artifactId>-->
<!--        </dependency>-->

        <dependency>
            <groupId>com.sutran.sd</groupId>
            <artifactId>sutran-sd-framework</artifactId>
        </dependency>

        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-text</artifactId>
            <version>1.1</version>
        </dependency>

        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>dashscope-sdk-java</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-pool2</artifactId>
        </dependency>

        <!-- Java WebSocket-->
        <dependency>
            <groupId>org.java-websocket</groupId>
            <artifactId>Java-WebSocket</artifactId>
            <version>1.5.6</version>
        </dependency>

    </dependencies>

</project>
