<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.sutran.sd</groupId>
        <artifactId>sutran-sd-v1</artifactId>
        <version>0.0.1</version>
    </parent>
    <packaging>pom</packaging>
    <artifactId>sutran-sd-modules</artifactId>

    <modules>
        <module>sutran-sd-module-system</module>
        <module>sutran-sd-module-user</module>
        <module>sutran-sd-module-oss</module>
        <module>sutran-sd-module-sms</module>
        <module>sutran-sd-module-generator</module>
        <module>sutran-sd-module-ai</module>
        <module>sutran-sd-module-pay</module>
        <module>sutran-sd-module-draw</module>
        <module>sutran-sd-module-design</module>
    </modules>
</project>
