package com.sutran.sd.framework.mq;

/**
 * @author zj
 * @date 2024-03-06
 */
public interface MqConstant {

    String SD_TXT_TO_IMG_DRAW_EXCHANGE = "SD_TXT_TO_IMG_DRAW_EXCHANGE";
    String SD_TXT_TO_IMG_DRAW_QUEUE = "SD_TXT_TO_IMG_DRAW_QUEUE";
    String SD_TXT_TO_IMG_DRAW_ROUTING_KEY = "SD_TXT_TO_IMG_DRAW_ROUTING_KEY";


    String SD_IMG_TO_IMG_DRAW_EXCHANGE = "SD_IMG_TO_IMG_DRAW_EXCHANGE";
    String SD_IMG_TO_IMG_DRAW_QUEUE = "SD_IMG_TO_IMG_DRAW_QUEUE";
    String SD_IMG_TO_IMG_DRAW_ROUTING_KEY = "SD_IMG_TO_IMG_DRAW_ROUTING_KEY";


    String SD_PRE_IMG_TASK_EXCHANGE = "SD_PRE_IMG_TASK_EXCHANGE";
    String SD_PRE_IMG_TASK_QUEUE = "SD_PRE_IMG_TASK_QUEUE";
    String SD_PRE_IMG_TASK_ROUTING_KEY = "SD_PRE_IMG_TASK_ROUTING_KEY";


    String SD_TRAIN_TASK_EXCHANGE = "SD_TRAIN_TASK_EXCHANGE";
    String SD_TRAIN_TASK_QUEUE = "SD_TRAIN_TASK_QUEUE";
    String SD_TRAIN_TASK_ROUTING_KEY = "SD_TRAIN_TASK_ROUTING_KEY";


    String WX_MSG_EXCHANGE = "WX_MSG_EXCHANGE";
    String WX_MSG_QUEUE = "WX_MSG_QUEUE";
    String WX_MSG_ROUTING_KEY = "WX_MSG_ROUTING_KEY";


    String NEW_WX_MSG_EXCHANGE = "NEW_WX_MSG_EXCHANGE";
    String NEW_WX_MSG_QUEUE = "NEW_WX_MSG_QUEUE";
    String NEW_WX_MSG_ROUTING_KEY = "NEW_WX_MSG_ROUTING_KEY";



    String IMG_SEND_THIRD_EXCHANGE = "IMG_SEND_THIRD_EXCHANGE";
    String IMG_SEND_THIRD_QUEUE = "IMG_SEND_THIRD_QUEUE";
    String IMG_SEND_THIRD_ROUTING_KEY = "IMG_SEND_THIRD_ROUTING_KEY";


    String SD_COMFY_DRAW_EXCHANGE = "SD_COMFY_DRAW_EXCHANGE";
    String SD_COMFY_DRAW_QUEUE = "SD_COMFY_DRAW_QUEUE";
    String SD_COMFY_DRAW_ROUTING_KEY = "SD_COMFY_DRAW_ROUTING_KEY";


    String SD_FLUXGYM_TRAIN_EXCHANGE = "SD_FLUXGYM_TRAIN_EXCHANGE";
    String SD_FLUXGYM_TRAIN_QUEUE = "SD_FLUXGYM_TRAIN_QUEUE";
    String SD_FLUXGYM_TRAIN_ROUTING_KEY = "SD_FLUXGYM_TRAIN_ROUTING_KEY";


    /** 支付超时队列 **/
    String PAY_ORDER_TIMEOUT_EXCHANGE = "PAY_ORDER_TIMEOUT_EXCHANGE";
    String PAY_ORDER_TIMEOUT_QUEUE = "MEMBER_PAY_ORDER_TIMEOUT_QUEUE";
    String PAY_ORDER_TIMEOUT_ROUTING_KEY = "MEMBER_PAY_ORDER_TIMEOUT_ROUTING_KEY";


    /** ---------------------------------------------------------------------------- 众筹支付订单 Direct exchange --------------------------------------------------------------------------- */
    String CROWDFUNDING_PAYMENT_ORDER_EXCHANGE = "CROWDFUNDING_PAYMENT_ORDER_EXCHANGE";
    String CROWDFUNDING_PAYMENT_ORDER_QUEUE = "CROWDFUNDING_PAYMENT_ORDER_QUEUE";
    String CROWDFUNDING_PAYMENT_ORDER_ROUTING_KEY = "CROWDFUNDING_PAYMENT_ORDER_ROUTING_KEY";
}
