<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.sutran.sd</groupId>
        <artifactId>sutran-sd-modules</artifactId>
        <version>0.0.1</version>
    </parent>

    <artifactId>sutran-sd-module-webui</artifactId>

    <description>
        SD WEBUI API模块
    </description>

    <dependencies>

        <!-- 训练模块-->
        <dependency>
            <groupId>com.sutran.sd</groupId>
            <artifactId>sutran-sd-module-train</artifactId>
        </dependency>

    </dependencies>

</project>
