<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.sutran.sd</groupId>
        <artifactId>sutran-sd-modules</artifactId>
        <version>0.0.1</version>
    </parent>

    <artifactId>sutran-sd-module-ai</artifactId>

    <description>
        ai模块
    </description>

    <dependencies>

        <!-- 通用工具-->
        <dependency>
            <groupId>com.sutran.sd</groupId>
            <artifactId>sutran-sd-common</artifactId>
        </dependency>

        <!-- 系统模块-->
        <dependency>
            <groupId>com.sutran.sd</groupId>
            <artifactId>sutran-sd-module-system</artifactId>
        </dependency>

        <!-- OSS功能模块 -->
        <dependency>
            <groupId>com.sutran.sd</groupId>
            <artifactId>sutran-sd-module-oss</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-text</artifactId>
        </dependency>

        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>dashscope-sdk-java</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-pool2</artifactId>
        </dependency>

        <!-- LangChain4j -->
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j</artifactId>
        </dependency>
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-open-ai</artifactId>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>dev.langchain4j</groupId>-->
<!--            <artifactId>langchain4j-dashscope</artifactId>-->
<!--        </dependency>-->

    </dependencies>

</project>
